01:53:00.527 [main] INFO  c.e.weblibrary.WebLibraryApplication - Starting WebLibraryApplication using Java 17.0.7 with PID 9796 (C:\Users\Ruslan\IdeaProjects\web-library\target\classes started by Ruslan in C:\Users\Ruslan\IdeaProjects\web-library)
01:53:00.529 [main] INFO  c.e.weblibrary.WebLibraryApplication - No active profile set, falling back to 1 default profile: "default"
01:53:00.864 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
01:53:00.895 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 27 ms. Found 4 JPA repository interfaces.
01:53:01.144 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
01:53:01.149 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
01:53:01.149 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
01:53:01.149 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.8]
01:53:01.190 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
01:53:01.190 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 640 ms
01:53:01.251 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
01:53:01.334 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@24a0c58b
01:53:01.334 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
01:53:01.404 [main] INFO  liquibase.database - Set default schema name to public
01:53:01.512 [main] INFO  liquibase.changelog - Reading from public.databasechangelog
01:53:01.516 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.544 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.545 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.547 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.558 [main] INFO  liquibase.lockservice - Successfully acquired change log lock
01:53:01.574 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.575 [main] INFO  liquibase.changelog - Reading from public.databasechangelog
01:53:01.576 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.576 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.596 [main] ERROR liquibase.changelog - ChangeSet liquibase/changesets/create_auth_user.yml::3::developer encountered an exception.
01:53:01.596 [main] INFO  liquibase - Update command encountered an exception.
01:53:01.597 [main] INFO  liquibase.executor - Changelog query completed.
01:53:01.597 [main] INFO  liquibase.lockservice - Successfully released change log lock
01:53:01.598 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changesets/create_auth_user.yml::3::developer:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "auth_user" уже существует [Failed SQL: (0) CREATE TABLE public.auth_user (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255), username VARCHAR(255), CONSTRAINT auth_user_pkey PRIMARY KEY (id))]
01:53:01.599 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
01:53:01.628 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
01:53:01.630 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
01:53:01.636 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLogger - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
01:53:01.645 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changesets/create_auth_user.yml::3::developer:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "auth_user" уже существует [Failed SQL: (0) CREATE TABLE public.auth_user (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255), username VARCHAR(255), CONSTRAINT auth_user_pkey PRIMARY KEY (id))]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
	at com.example.weblibrary.WebLibraryApplication.main(WebLibraryApplication.java:12)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changesets/create_auth_user.yml::3::developer:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "auth_user" уже существует [Failed SQL: (0) CREATE TABLE public.auth_user (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255), username VARCHAR(255), CONSTRAINT auth_user_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:297)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:295)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Liquibase.runInScope(Liquibase.java:2639)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 18 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changesets/create_auth_user.yml::3::developer:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "auth_user" уже существует [Failed SQL: (0) CREATE TABLE public.auth_user (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255), username VARCHAR(255), CONSTRAINT auth_user_pkey PRIMARY KEY (id))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:744)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:59)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:105)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Scope.child(Scope.java:260)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:75)
	... 36 common frames omitted
Caused by: liquibase.exception.DatabaseException: ОШИБКА: отношение "auth_user" уже существует [Failed SQL: (0) CREATE TABLE public.auth_user (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, password VARCHAR(255), username VARCHAR(255), CONSTRAINT auth_user_pkey PRIMARY KEY (id))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1270)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1252)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:702)
	... 56 common frames omitted
Caused by: org.postgresql.util.PSQLException: ОШИБКА: отношение "auth_user" уже существует
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441)
	... 61 common frames omitted
